"""empty message

Revision ID: d4e23258afd6
Revises: b412a1286d84
Create Date: 2019-08-28 10:33:59.430263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4e23258afd6'
down_revision = 'b412a1286d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', sa.String(length=100), nullable=True))
    op.drop_column('cms_user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('password', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###
